export enum LoginPages {
  LOGIN = 'LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  SUCCESSFULL_LOGIN = 'SUCCESSFULL_LOGIN',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  VALIDATE_OTP = 'VALIDATE_OTP',
  SUCCESSFULLY_CHANGED_PASSWORD = 'SUCCESSFULLY_CHANGED_PASSWORD',
}
