export const dates = [
  {
    title: 'title',
    workingDay: '2023-09-05',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:00',
    lunchEndTime: '13:00',
    approvalFlag: true,
    reasonForLeave: 'string',
    scheduleType: 'string',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY'],
  },
  {
    title: 'title',
    workingDay: '2023-09-11',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:00',
    lunchEndTime: '13:00',
    approvalFlag: true,
    reasonForLeave: 'string',
    scheduleType: 'string',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY'],
  },
  {
    title: 'title',
    workingDay: '2023-09-12',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:00',
    lunchEndTime: '13:00',
    approvalFlag: true,
    reasonForLeave: 'string',
    scheduleType: 'string',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY'],
  },
  {
    title: 'weekdays-working',
    workingDay: '2023-09-05',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:15',
    lunchEndTime: '13:15',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
  },
  {
    title: 'weekdays-working',
    workingDay: '2023-09-06',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:15',
    lunchEndTime: '13:15',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
  },
  {
    title: 'weekdays-working',
    workingDay: '2023-09-07',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:15',
    lunchEndTime: '13:15',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
  },
  {
    title: 'weekdays-working',
    workingDay: '2023-09-08',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:15',
    lunchEndTime: '13:15',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
  },
  {
    title: 'weekdays-working',
    workingDay: '2023-09-11',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:15',
    lunchEndTime: '13:15',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
  },
  {
    title: 'weekdays-working',
    workingDay: '2023-09-12',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:15',
    lunchEndTime: '13:15',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
  },
  {
    title: 'weekday-working',
    workingDay: '2023-09-11',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:15',
    lunchEndTime: '13:15',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY'],
  },
  {
    title: 'weekday-working',
    workingDay: '2023-09-12',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:15',
    lunchEndTime: '13:15',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY'],
  },
  {
    title: 'weekday-working',
    workingDay: '2023-09-13',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:15',
    lunchEndTime: '13:15',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY'],
  },
  {
    title: 'weekday-working',
    workingDay: '2023-09-14',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '12:15',
    lunchEndTime: '13:15',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY'],
  },
  {
    title: 'working-hours-title',
    workingDay: '2023-09-11',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '11:00',
    lunchEndTime: '12:00',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'FRIDAY'],
  },
  {
    title: 'working-hours-title',
    workingDay: '2023-09-12',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '11:00',
    lunchEndTime: '12:00',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'FRIDAY'],
  },
  {
    title: 'working-hours-title',
    workingDay: '2023-09-13',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '11:00',
    lunchEndTime: '12:00',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'FRIDAY'],
  },
  {
    title: 'working-hours-title',
    workingDay: '2023-09-15',
    startTime: '09:00',
    endTime: '17:00',
    lunchStartTime: '11:00',
    lunchEndTime: '12:00',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: null,
    leaveEndTime: null,
    startDate: null,
    endDate: null,
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'FRIDAY'],
  },
  {
    title: 'only weekends',
    workingDay: '2023-09-10',
    startTime: '09:00',
    endTime: '18:00',
    lunchStartTime: '12:30',
    lunchEndTime: '13:00',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: '',
    leaveEndTime: '',
    startDate: '2023-09-10',
    endDate: '2023-09-17',
    listOfDays: ['SATURDAY', 'SUNDAY'],
  },
  {
    title: 'only weekends',
    workingDay: '2023-09-16',
    startTime: '09:00',
    endTime: '18:00',
    lunchStartTime: '12:30',
    lunchEndTime: '13:00',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: '',
    leaveEndTime: '',
    startDate: '2023-09-10',
    endDate: '2023-09-17',
    listOfDays: ['SATURDAY', 'SUNDAY'],
  },
  {
    title: 'only weekends',
    workingDay: '2023-09-17',
    startTime: '09:00',
    endTime: '18:00',
    lunchStartTime: '12:30',
    lunchEndTime: '13:00',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: '',
    leaveStartTime: '',
    leaveEndTime: '',
    startDate: '2023-09-10',
    endDate: '2023-09-17',
    listOfDays: ['SATURDAY', 'SUNDAY'],
  },
  {
    title: 'weekends only',
    workingDay: '2023-09-09',
    startTime: '09:15',
    endTime: '18:00',
    lunchStartTime: '13:00',
    lunchEndTime: '14:00',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: 'WORKING_HOUR',
    leaveStartTime: '',
    leaveEndTime: '',
    startDate: '2023-09-05',
    endDate: '2023-09-12',
    listOfDays: ['SATURDAY', 'SUNDAY'],
  },
  {
    title: 'weekends only',
    workingDay: '2023-09-10',
    startTime: '09:15',
    endTime: '18:00',
    lunchStartTime: '13:00',
    lunchEndTime: '14:00',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: 'WORKING_HOUR',
    leaveStartTime: '',
    leaveEndTime: '',
    startDate: '2023-09-05',
    endDate: '2023-09-12',
    listOfDays: ['SATURDAY', 'SUNDAY'],
  },
  {
    title: 'hours',
    workingDay: '2023-09-12',
    startTime: '09:30',
    endTime: '18:00',
    lunchStartTime: '11:00',
    lunchEndTime: '12:00',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: 'WORKING_HOURS',
    leaveStartTime: '',
    leaveEndTime: '',
    startDate: '2023-09-12',
    endDate: '2023-09-13',
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
  },
  {
    title: 'hours',
    workingDay: '2023-09-13',
    startTime: '09:30',
    endTime: '18:00',
    lunchStartTime: '11:00',
    lunchEndTime: '12:00',
    approvalFlag: true,
    reasonForLeave: '',
    scheduleType: 'WORKING_HOURS',
    leaveStartTime: '',
    leaveEndTime: '',
    startDate: '2023-09-12',
    endDate: '2023-09-13',
    listOfDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
  },
];
