name: Frontend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
  
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Replace string in file
        uses: MathieuSoysal/replace-string-in-file@v1.0.0
        with:
          file: .env.example
          old-string: url
          new-string: ${{ vars.BEURL }}
        
         
